from typing import Literal

ChatMessageType = Literal['message', 'notice', 'status']

ChatMessageSubType = Literal[
    'custom_reward_redemption',
    'sub',
    'resub',
    'sub_gift',
    'community_sub_gift',
    'gift_paid_upgrade',
    'prime_paid_upgrade',
    'pay_it_forward',
    'raid',
    'unraid',
    'announcement',
    'bits_badge_tier',
    'ban',
    'timeout',
    'unban',
    'untimeout',
    'clear',
    'emoteonly',
    'emoteonlyoff',
    'followers',
    'followersoff',
    'uniquechat',
    'uniquechatoff',
    'slow',
    'slowoff',
    'subscribers',
    'subscribersoff',
    'unraid',
    'delete',
    'vip',
    'unvip',
    'raid',
    'add_blocked_term',
    'add_permitted_term',
    'remove_blocked_term',
    'remove_permitted_term',
    'mod',
    'unmod',
    'approve_unban_request',
    'deny_unban_request',
    'warn',
    'text',
    'channel_points_highlighted',
    'channel_points_sub_only',
    'user_intro',
    'power_ups_message_effect',
    'power_ups_gigantified_emote',
]
