[project]
name = "tbot"
version = "2.0"
description = "Twitch, Discord and YouTube bot"
dependencies = [
    "twitchAPI==4.3.1",
    "fastapi==0.115.4",
    "sqlalchemy==2.0.36",
    "yaml-settings-pydantic==2.3.2",
    "pydantic==2.9.2",
    "redis==5.2.0",
    "httpx[http2]==0.27.2",
    "httpx_auth==0.22.0",
    "click==8.0.1",
    "uvicorn==0.32.0",
    "honcho==2.0.0",
    "arq==0.26.1",
    "asyncmy==0.2.9",
    "alembic==1.14.0",
    "uuid6==2024.7.10",
    "humanize==4.11.0",
    "python-dateutil==2.9.0.post0",
]

[project.optional-dependencies]
dev = [
    "pytest-httpx==0.33.0",
    "pytest==8.3.3",
    "pytest-asyncio==0.24.0",
    "pytest-mock-3.14.0",
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core>=3.2,<4"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
