import random
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession
from uuid6 import uuid7

from tbot2.common import ChatMessageCreate

from ..actions.chat_message_actions import create_chat_message


async def seed_chat_messages(
    *, channel_id: UUID, num_messages: int = 15, session: AsyncSession | None = None
) -> None:
    usernames: list[tuple[str, str]] = [
        ('viewer1', 'Viewer One'),
        ('gamer123', 'GamerPro123'),
        ('chatfan', 'ChatFan'),
        ('streamer_friend', 'StreamerFriend'),
        ('new_user', 'NewUser'),
        ('loyal_sub', 'LoyalSubscriber'),
        ('random_chatter', 'RandomChatter'),
        ('excited_fan', 'ExcitedFan'),
        ('lurker42', 'Lurker42'),
        ('emoji_lover', 'EmojiLover😊'),
        ('pro_player', 'ProPlayer'),
        ('mod_jane', 'ModJane'),
        ('superfan99', 'SuperFan99'),
        ('silent_watcher', 'SilentWatcher'),
        ('emote_master', 'EmoteMaster'),
        ('nightbot', 'NightBot'),
        ('hype_train', 'HypeTrain'),
        ('tech_guru', 'TechGuru'),
        ('music_lover', 'MusicLover'),
        ('quizmaster', 'QuizMaster'),
        ('retro_gamer', 'RetroGamer'),
        ('speedrunner', 'SpeedRunner'),
        ('casual_viewer', 'CasualViewer'),
        ('vip_alex', 'VIPAlex'),
        ('meme_lord', 'MemeLord'),
        ('tiktok_star', 'TikTokStar'),
        ('yt_commenter', 'YTCommenter'),
        ('twitch_fan', 'TwitchFan'),
        ('yt_gamer', 'YTGamer'),
        ('ttk_viewer', 'TTKViewer'),
        ('alpha_wolf', 'AlphaWolf'),
        ('beta_tester', 'BetaTester'),
        ('pixel_pirate', 'PixelPirate'),
        ('stream_queen', 'StreamQueen'),
        ('king_kappa', 'KingKappa'),
        ('emote_spammer', 'EmoteSpammer'),
        ('clipper', 'Clipper'),
        ('mod_mike', 'ModMike'),
        ('vip_sam', 'VIPSamantha'),
        ('retro_andy', 'RetroAndy'),
        ('quiz_wiz', 'QuizWiz'),
        ('snack_attack', 'SnackAttack'),
        ('late_night_owl', 'LateNightOwl'),
        ('early_bird', 'EarlyBird'),
        ('hype_beast', 'HypeBeast'),
        ('silent_shadow', 'SilentShadow'),
        ('cosplay_hero', 'CosplayHero'),
        ('anime_fan', 'AnimeFan'),
        ('sports_buff', 'SportsBuff'),
        ('coding_ninja', 'CodingNinja'),
        ('music_maniac', 'MusicManiac'),
        ('pet_lover', 'PetLover'),
        ('travel_bug', 'TravelBug'),
        ('foodie', 'Foodie'),
        ('gadget_guru', 'GadgetGuru'),
        ('movie_buff', 'MovieBuff'),
        ('bookworm', 'Bookworm'),
        ('challenge_ace', 'ChallengeAce'),
        ('fan_artist', 'FanArtist'),
        ('setup_master', 'SetupMaster'),
        ('holiday_hype', 'HolidayHype'),
        ('behind_scenes', 'BehindScenes'),
        ('app_addict', 'AppAddict'),
        ('color_craze', 'ColorCraze'),
        ('animal_friend', 'AnimalFriend'),
        ('cooking_star', 'CookingStar'),
        ('sporty_spirit', 'SportySpirit'),
        ('giveaway_guru', 'GiveawayGuru'),
        ('quote_king', 'QuoteKing'),
        ('sub_star', 'SubStar'),
        ('drink_enthusiast', 'DrinkEnthusiast'),
        ('stream_runner', 'StreamRunner'),
        ('holiday_hero', 'HolidayHero'),
        ('tour_guide', 'TourGuide'),
        ('challenge_champ', 'ChallengeChamp'),
        ('moment_maker', 'MomentMaker'),
        ('reaction_queen', 'ReactionQueen'),
        ('console_collector', 'ConsoleCollector'),
        ('setup_show', 'SetupShow'),
        ('songbird', 'SongBird'),
        ('dance_star', 'DanceStar'),
        ('food_fanatic', 'FoodFanatic'),
        ('horror_gamer', 'HorrorGamer'),
        ('movie_maniac', 'MovieManiac'),
        ('collab_creator', 'CollabCreator'),
        ('color_lover', 'ColorLover'),
        ('retro_fan', 'RetroFan'),
        ('animal_enthusiast', 'AnimalEnthusiast'),
        ('cook_master', 'CookMaster'),
        ('sport_fan', 'SportFan'),
        ('giveaway_star', 'GiveawayStar'),
        ('quote_queen', 'QuoteQueen'),
        ('sub_supporter', 'SubSupporter'),
        ('drink_master', 'DrinkMaster'),
        ('stream_marathon', 'StreamMarathon'),
        ('holiday_fan', 'HolidayFan'),
        ('bts_buff', 'BTSBuff'),
        ('book_buddy', 'BookBuddy'),
        ('tour_star', 'TourStar'),
        ('app_fan', 'AppFan'),
        ('challenge_fan', 'ChallengeFan'),
        ('moment_fan', 'MomentFan'),
        ('fanart_fan', 'FanArtFan'),
    ]

    messages: list[str] = [
        'Hello everyone!',
        'How is the stream today?',
        'LOL that was funny',
        'Great play!',
        'I love this game',
        'First time watching, this is awesome',
        'Can you explain what just happened?',
        'Followed! Great content',
        'Where are you from?',
        'GG',
        'PogChamp',
        'How long have you been streaming?',
        'Any tips for beginners?',
        'This music is great',
        'What settings do you use?',
        "Let's go!",
        'That was epic!',
        'Can you do a shoutout?',
        'Sub hype!',
        'Who else is watching from mobile?',
        'I just joined, what did I miss?',
        'This chat is wild!',
        'Love the energy here!',
        'Can you play my favorite song?',
        'When is the next stream?',
        'This is trending on TikTok!',
        'Saw this on YouTube Shorts!',
        'Twitch chat is the best!',
        'Anyone else from TikTok?',
        'YT gang here!',
        "Let's get some hype in the chat!",
        'Streamer deserves more viewers!',
        'What platform do you prefer?',
        'This is my favorite channel!',
        'Can you react to this meme?',
        'Who else is grinding tonight?',
        "Let's raid someone after!",
        'I clipped that moment!',
        'This is so wholesome!',
        'Can you say hi to me?',
        "I'm here every stream!",
        'Can you play another game?',
        'What is your favorite snack?',
        'The graphics look amazing!',
        'Who else is watching from Europe?',
        'Can you do a giveaway?',
        'I love your setup!',
        'What mic are you using?',
        'This is so relaxing.',
        'Can you show your pet?',
        'What time zone are you in?',
        'I just subscribed!',
        'Can you do a Q&A?',
        'What is your favorite streamer?',
        'This chat is so friendly!',
        'Can you do a challenge run?',
        'What is your favorite emote?',
        'How do you stay so positive?',
        'Can you play with viewers?',
        'What is your stream schedule?',
        'This is the best part!',
        'Can you speak another language?',
        'What is your favorite moment on stream?',
        'Can you do a speedrun?',
        'Who else is here every day?',
        'What is your favorite meme?',
        'Can you do a reaction stream?',
        'What is your favorite console?',
        'Can you show your setup?',
        'What is your favorite song?',
        'Can you do a dance?',
        'What is your favorite food?',
        'Can you play horror games?',
        'What is your favorite movie?',
        'Can you do a collab?',
        'What is your favorite color?',
        'Can you play retro games?',
        'What is your favorite animal?',
        'Can you do a cooking stream?',
        'What is your favorite sport?',
        'Can you do a giveaway soon?',
        'What is your favorite quote?',
        'Can you play with subs?',
        'What is your favorite drink?',
        'Can you do a 24-hour stream?',
        'What is your favorite holiday?',
        'Can you do a behind-the-scenes?',
        'What is your favorite book?',
        'Can you do a setup tour?',
        'What is your favorite app?',
        'Can you do a challenge?',
        'What is your favorite streamer moment?',
        'Can you do a reaction to fan art?',
    ]

    providers: list[str] = ['twitch', 'youtube', 'tiktok']

    for _ in range(num_messages):
        username, display_name = random.choice(usernames)
        provider_channel_id = str(random.randint(10000, 99999))
        message = random.choice(messages)
        provider = random.choice(providers)

        await create_chat_message(
            ChatMessageCreate(
                type='message',
                channel_id=channel_id,
                provider_viewer_id=provider_channel_id,
                viewer_name=username,
                viewer_display_name=display_name,
                provider_message_id=str(uuid7()),
                provider=provider,
                provider_channel_id=provider_channel_id,
                message=message,
            ),
            session=session,
        )
